import json
import datetime
import html
from urllib.parse import urlparse

def generate_html_report(repo_url: str, detailed_issues: list, is_clean: bool, summary: str) -> str:
    """
    Generates a minimalist, monotone HTML report based on the findings.
    """
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    repo_name = urlparse(repo_url).path.strip('/')
    if not repo_name:
        repo_name = repo_url
        
    status_text = "PASSED" if is_clean else "FAILED"
    
    # Generate rows
    rows_html = ""
    for issue in detailed_issues:
        sev = html.escape(str(issue.get('severity', 'UNKNOWN')))
        cat = html.escape(str(issue.get('category', 'UNKNOWN')))
        msg = html.escape(str(issue.get('message', 'N/A')))
        rows_html += f"""
            <tr>
                <td>{sev}</td>
                <td>{cat}</td>
                <td>{msg}</td>
            </tr>
        """
        
    if not detailed_issues:
        rows_html = """
            <tr>
                <td colspan="3" class="text-center">No vulnerabilities found. Codebase is clean.</td>
            </tr>
        """
        
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RepoShield Audit Report: {repo_name}</title>
    <style>
        body {{
            font-family: 'Courier New', Courier, monospace;
            background-color: #ffffff;
            color: #000000;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1000px;
            margin: 0 auto;
            border: 2px solid #000000;
            padding: 30px;
        }}
        h1, h2, h3 {{
            text-transform: uppercase;
            border-bottom: 2px solid #000000;
            padding-bottom: 10px;
        }}
        .meta-info {{
            margin-bottom: 30px;
        }}
        .meta-info p {{
            margin: 5px 0;
            font-weight: bold;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }}
        th, td {{
            border: 1px solid #000000;
            padding: 12px;
            text-align: left;
        }}
        th {{
            background-color: #000000;
            color: #ffffff;
            text-transform: uppercase;
        }}
        .text-center {{
            text-align: center;
        }}
        .status-passed {{
            color: #000000;
            border: 2px solid #000000;
            padding: 5px 10px;
            display: inline-block;
        }}
        .status-failed {{
            color: #ffffff;
            background-color: #000000;
            padding: 5px 10px;
            display: inline-block;
        }}
        .footer {{
            margin-top: 50px;
            text-align: center;
            font-size: 0.9em;
            border-top: 1px solid #000000;
            padding-top: 10px;
        }}
    </style>
</head>
<body>

<div class="container">
    <h1>RepoShield Security Audit</h1>
    
    <div class="meta-info">
        <p>Target Repository: <span>{repo_url}</span></p>
        <p>Scan Date: <span>{timestamp}</span></p>
        <p>Overall Status: <span class="{'status-passed' if is_clean else 'status-failed'}">{status_text}</span></p>
        <p>Summary: <span>{summary}</span></p>
    </div>

    <h2>Detailed Findings</h2>
    <table>
        <thead>
            <tr>
                <th style="width: 15%">Severity</th>
                <th style="width: 20%">Category</th>
                <th style="width: 65%">Description</th>
            </tr>
        </thead>
        <tbody>
            {rows_html}
        </tbody>
    </table>
    
    <div class="footer">
        Generated by RepoShield Zero-Trust CLI
    </div>
</div>

</body>
</html>
"""
    return html_content